### ISSUE TITLE
Getting App Metrics fails in release 66

### ISSUE THREAD

**Issue by antitux** [DataDog/datadog-firehose-nozzle-release#26]
**Steps to reproduce the issue:**
1. Set `cc.endpoint`
2. set `nozzle.app_metrics` to `true`
3. deploy 

**Describe the results you received:**
getting app metrics fails:

`{"timestamp":1518625733.905645370,"process_id":6930,"source":"datadog-firehose-nozzle","log_level":"error","message":"there was an error grabbing data for app a4c654ed-2687-46f5-95a6-e12724e5f0e3: Error requesting apps: cfclient: error (1000): CF-InvalidAuthToken","data":null,"file":"/var/vcap/data/compile/datadog-firehose-nozzle/datadog-firehose-nozzle/src/github.com/DataDog/datadog-firehose-nozzle/appmetrics/app_metrics.go","line":225,"method":"github.com/DataDog/datadog-firehose-nozzle/appmetrics.(*AppMetrics).ParseAppMetric"}`

**Describe the results you expected:**

Getting app metrics should be successful.

**Additional information you deem important (e.g. issue happens only occasionally):**

This does work when running in standalone firehose nozzle binary based off master with identical configuration.

**Comment by gmmeyer** [comment]
@antitux it seems like your UAA auth token is invalid. It needs to be updated to allow you to grab application metrics from the Cloud Controller. I think the guildelines on this release's readme might now be incorrect as to what you need to have in order to grab them. I need to check. However, if you're using the CLI to get a token, this command will work:

```
uaac client add datadog-firehose-nozzle \
    --name datadog-firehose-nozzle \
    --scope doppler.firehose,cloud_controller.admin_read_only,oauth.login \
    --authorities doppler.firehose,cloud_controller.admin_read_only,openid,oauth.approvals \
    --authorized_grant_types client_credentials,refresh_token \
    --access_token_validity 1209600 \
    -s $CLIENT_SECRET
```

**Comment by gmmeyer** [comment]
@antitux I looked, the guidelines there are incorrect. I need to update them! Thank you for this bug report. I will let you know when I update them and close this bug

**Comment by antitux** [comment]
@gmmeyer, you were correct. Updating uaa to the guidelines in #30 resolved the issue.

Thanks!

**Comment by gmmeyer** [comment]
@antitux awesome! I'm glad it helped. Sorry it was unclear before!

**Comment by gmmeyer** [comment]
@antitux now that #30 is merged I am going to close this issue! Thanks again for your feedback, it was very valuable!
