### ISSUE TITLE
Bump Golang to 1.13 

### ISSUE THREAD

**Issue by robertjsullivan** [DataDog/datadog-firehose-nozzle-release#84]
I noticed that the release includes a Golang 1.9 blob.  This version of Golang is no longer in support.  Please bump it to 1.13.  I would PR it, but I don't have upload access to the blob store.

**Comment by zippolyte** [comment]
https://github.com/DataDog/datadog-firehose-nozzle-release/pull/86 addresses that, closing.

We'll cut the release soon.
Thanks !
