### ISSUE TITLE
Bump version to include the new changes in the firehose

### ISSUE THREAD

**Issue by bwinter** [DataDog/datadog-firehose-nozzle-release#85]
**Steps to reproduce the issue:**
1. Via the Github UI one can see the recent commit in the nozzle is not included in the release.

**Describe the results you expected:**
I would like to see this commit in a new release so we no longer need to hard code a dev version of the nozzle. This will allow us to more easily stay up-to-date with future changes.

---
Specifically we would like to have the recently added resilience to NaN data points. (I work with the folks who made that PR)

Thanks!

**Comment by nmuesch** [comment]
Hey @bwinter We just released the latest version of the nozzle that includes this change (See releases - https://github.com/DataDog/datadog-firehose-nozzle-release/releases/tag/76 I'll go ahead and close this out.
